export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCTS_FETCHING_ERROR = 'PRODUCTS_FETCHING_ERROR';
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";